### ISSUE TITLE
There is a training set path in the input file, but after converting to v2, the training set path disappears

### ISSUE THREAD

**Issue by XuFanffei** [deepmodeling/dpgen#1268]
In the training step of dpgen, there is a training set path in the input file, but after converting to v2, the training set path disappears. I have checked t

**Comment by XuFanffei** [comment]
I have checked the path of the training set in the param file and there is no problem.

**Comment by njzjz** [comment]
Please provide a sample.

**Comment by iProzd** [comment]
This issue has been sovled. The user provided the `input.json` in a strange format.
It has both `training`/`systems` and `training`/`training_data`/`systems`, the former is empty. Whatever the latter is, it will unexpectedly choose the empty `training`/`systems`. 

This should be fixed in DeePMD-kit: [#2656](https://github.com/deepmodeling/deepmd-kit/issues/2656).
