### ISSUE TITLE
A strange error

### ISSUE THREAD

**Issue by Xi-yuanWang** [deepmodeling/dpgen#314]
INFO:dpgen:-------------------------iter.000000 task 01--------------------------
INFO:dpgen:new submission of 6b33f4ab-ee6f-46a3-8b5e-010c8f50b303 for chunk 8aefb06c426e07a0a671a1e2488b4858d694a730
INFO:dpgen:new submission of 3dd38ba5-1aab-47b6-aa9d-a595219da418 for chunk e193a01ecf8d30ad0affefd332ce934e32ffce72
INFO:dpgen:new submission of 06bf77bf-c80b-4d54-b89d-5308703421e8 for chunk 6fc978af728d43c59faa400d5f6e0471ac850d4c
INFO:dpgen:new submission of b20f8073-24c8-4f68-a99c-02672ca961ca for chunk 221407c03ae5c73109cce71d27e24637824f3333
INFO:dpgen:job 6b33f4ab-ee6f-46a3-8b5e-010c8f50b303 finished
INFO:dpgen:job 06bf77bf-c80b-4d54-b89d-5308703421e8 finished
INFO:dpgen:job 3dd38ba5-1aab-47b6-aa9d-a595219da418 finished
INFO:dpgen:job b20f8073-24c8-4f68-a99c-02672ca961ca finished
INFO:dpgen:-------------------------iter.000000 task 02--------------------------
INFO:dpgen:-------------------------iter.000000 task 03--------------------------
Traceback (most recent call last):
  File "/nfs-share/home/1800011848/.local/bin/dpgen", line 8, in <module>
    sys.exit(main())
  File "/nfs-share/home/1800011848/.local/lib/python3.8/site-packages/dpgen/main.py", line 182, in main
    args.func(args)
  File "/nfs-share/home/1800011848/.local/lib/python3.8/site-packages/dpgen/generator/run.py", line 2309, in gen_run
    run_iter (args.PARAM, args.MACHINE)
  File "/nfs-share/home/1800011848/.local/lib/python3.8/site-packages/dpgen/generator/run.py", line 2278, in run_iter
    cont = make_model_devi (ii, jdata, mdata)
  File "/nfs-share/home/1800011848/.local/lib/python3.8/site-packages/dpgen/generator/run.py", line 726, in make_model_devi
    system = dpdata.System(os.path.join(conf_path, poscar_name), fmt = fmt, type_map = jdata['type_map'])
  File "/nfs-share/home/1800011848/.local/lib/python3.8/site-packages/dpdata/system.py", line 120, in __init__
    self.from_fmt(file_name, fmt, type_map=type_map, begin= begin, step=step, **kwargs)
  File "/nfs-share/home/1800011848/.local/lib/python3.8/site-packages/dpdata/system.py", line 137, in from_fmt
    func(self, file_name, **kwargs)
  File "/nfs-share/home/1800011848/.local/lib/python3.8/site-packages/dpdata/system.py", line 565, in from_vasp_poscar
    with open(file_name) as fp:
IsADirectoryError: [Errno 21] Is a directory: 'iter.000000/01.model_devi/confs/000.0000.poscar'

And the iter.000000/01.model_devi/confs/000.0000.poscar is a symbolic link connected to the root.

**Comment by wxy20010110** [comment]
It seems to have something to do with the parameter "sys_configs"

**Comment by DingChangjie** [comment]
Here is a late comment on this problem(2021/5/15)...Hope this would help succeeding users, haha.

This problem is due to the **parsing rules** used by DpGen, i.e. a strict form of your "sys_configs_prefix" and "sys_configs" must be used. For example, you've put one of your configuration POSCARs in _./SystemConfigs/POSCAR_. Then you must begin your "sys_configs_prefix" WITHOUT slash, and end it WITH a slash: 
_"sys_configs_prefix": "SystemConfigs/",_
And you should write the "sys_configs" in a similar way, but this time end it WITH "POSCAR". In this example, things are easy:
_"sys_configs":	["POSCAR"],_

Multiple systems follow the same rules, except that you can write multiple paths in "sys_configs"

**Comment by AnguseZhang** [comment]
> Here is a late comment on this problem(2021/5/15)...Hope this would help succeeding users, haha.
> 
> This problem is due to the **parsing rules** used by DpGen, i.e. a strict form of your "sys_configs_prefix" and "sys_configs" must be used. For example, you've put one of your configuration POSCARs in _./SystemConfigs/POSCAR_. Then you must begin your "sys_configs_prefix" WITHOUT slash, and end it WITH a slash: _"sys_configs_prefix": "SystemConfigs/",_ And you should write the "sys_configs" in a similar way, but this time end it WITH "POSCAR". In this example, things are easy: _"sys_configs": ["POSCAR"],_
> 
> Multiple systems follow the same rules, except that you can write multiple paths in "sys_configs"

As fas as I know, there is not such restraint for `sys_configs_prefix`, and `sys_configs`. If there is any problem, you can re-open this issue or create a new issue with necessary descriptions to reproduce the problem. Thanks again for your helpful discussions.

**Comment by formocho** [comment]
I still have the same question but don't know how to solve it .can you give me the solution about you? I will appreciate it if you can answer me.

**Comment by HuangJiameng** [comment]
> I still have the same question but don't know how to solve it .can you give me the solution about you? I will appreciate it if you can answer me.

You can refer to https://github.com/deepmodeling/dpgen/blob/master/dpgen/generator/run.py#L797-L804. `sys_configs_prefix` is added to the front of paths in `sys_configs` with `os.path.join`.

**Comment by AroundPeking** [comment]
I have encountered the same issue. How can I do? Changing sys_configs_prefix helped nothing.

**Comment by SchrodingersCattt** [comment]
I am encountering the same issue.  

For example, my absolute path of POSCAR is `/home/MyName/DPGEN/data/sys1 and sys2`, and I tried the following combinations, but all failed: 

`"sys_configs_prefix: "data/",
"sys_configs":[["sys1"], ["sys2"]],`

and

`"sys_configs_prefix: "./data/",
"sys_configs":[["sys1"], ["sys2"]],`

and

`"sys_configs_prefix: "/home/MyName/DPGEN/data/",
"sys_configs": [["sys1"], ["sys2"]],`

and

"sys_configs": [["./data/sys1"], ["./data/sys2"]],`

and

"sys_configs": [["data/sys1"], ["data/sys2"]],`


May I ask if your problem was solved and how? Thank you!
