### ISSUE TITLE
A detailed document about para.json and machine.json

### ISSUE THREAD

**Issue by LiuGaoyong** [deepmodeling/dpgen#422]
**Summary**

Please provide a detailed document about para.json and machine.json for dpgen beginners.

For Examples, the doc file of the DPGEN package, and some example train set and para.json and machine.josn.

**Comment by AnguseZhang** [comment]
Definitely we will improve documentation, but this is an on-going process.

Examples jsons have been put at 
https://github.com/deepmodeling/dpgen/blob/devel/examples/run/dp1.x-lammps-vasp/CH4/param_CH4_deepmd-kit-1.1.0.json
and https://github.com/deepmodeling/dpgen/blob/devel/examples/machine/DeePMD-kit-1.x/machine-slurm-qe.json . 
The descriptions for all parameters in `param.json` are in manual.  https://github.com/deepmodeling/dpgen

You can first see these and raise your problem. Otherwise this issue is too general and not informative.

**Comment by LiuGaoyong** [comment]
Thanks.

**Comment by njzjz** [comment]
Documentation has been added:
- https://docs.deepmodeling.com/projects/dpgen/en/devel/run/example-of-param.html
- https://docs.deepmodeling.com/projects/dpgen/en/devel/run/example-of-machine.html
