### ISSUE TITLE
[BUG] _different trust level for different sys_idx_

### ISSUE THREAD

**Issue by FeiYang0106** [deepmodeling/dpgen#746]
**Summary**

When I set a list for _model_devi_f_trust_lo_ and _model_devi_f_trust_hi_ following https://github.com/deepmodeling/dpgen/pull/609, No matter how I change this parameter, excepting just one float, the problem is never solved.
A list I set
![image](https://user-images.githubusercontent.com/93854077/171305741-7fe94cef-c6ce-47f2-8547-cf092d0bcd09.png)

Error message
![image](https://user-images.githubusercontent.com/93854077/171305842-617f7589-f9c6-4909-8f72-b4ad3dac692f.png)

**DPGEN Version and Platform**

DPGEN version : 0.10.5

**Further Information, Files, and Links**

I also attempt to modify the resource code in dpgen/generator/run.py, line 1757-1760, 'ss' is changed to 'int(ss)'
![image](https://user-images.githubusercontent.com/93854077/171306681-f49856e9-18a9-4f89-b544-d00bebaf816e.png)

Now it works. But another question is:
The length of the list does not coordinate with the number of sys_idx. As long as the length of the list is larger than the number of sys_configs, it works. But does the aim of the list is to set different trust level for different sys_idx or sys_configs? you know the number of sys_idx is not equal to sys_configs. This change is likely to be set for different sys_configs. If I want to set different trust level for different sys_idx or each iteration step, what should I do?

**Comment by Cloudac7** [comment]
Sorry for replying after as long as a month passed, for no e-mail notification until I just checked the inbox (perhaps due to some issue, I guess. Sorry). I have read the original discussion as well as the issue, it seems that I forgot to convert string back to integer, would be fixed soon. 

> If I want to set different trust level for different sys_idx or each iteration step, what should I do?

It is an interesting enhancement for I just met the issue and now working to make it work. However, it is now global parameters that control the model deviation trust level. Would just covering them with local ones be a good idea?
